In [2]:
!pip uninstall TabularExperimentTrackerClient --y
!pip install git+https://github.com/DanielWarfield1/TabularExperimentTrackerClient

  Cloning https://github.com/DanielWarfield1/TabularExperimentTrackerClient to /tmp/pip-req-build-8vu_ffuh
  Running command git clone --filter=blob:none --quiet https://github.com/DanielWarfield1/TabularExperimentTrackerClient /tmp/pip-req-build-8vu_ffuh
  Resolved https://github.com/DanielWarfield1/TabularExperimentTrackerClient to commit df52eac0ce37df983d93a1b76cb9f4380a27b40d
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.3/131.3 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 6.7 MB/s eta 0:00:00
  Created wheel for TabularExperimentTrackerClient: filename=TabularExperimentTrackerClient-0.0.1-py3-none-any.whl size=6378 sha256=01e9589236a9810b0a5342f0fe7455ad827f53eadbb3250e026208de779217b7
  Stored in directory: /tmp/pip-ephem-wheel-cache-33v0ptwk/wheels/f9/2e/f3/69345202c956e07475c8f2f55074ad4d97b3e6a976b70fafab
  Created

In [3]:
!pip install numpy
!pip install pandas
!pip install scikit-learn
!pip install torch

In [4]:
from TabularExperimentTrackerClient.ExperimentClient import ExperimentClient

# ==== Setup ====
#creating experiment client utilities
ex = ExperimentClient(verbose = True)
if True:

    # BART

    #getting openml credentials from drive
    ex.define_opml_cred_drive('/My Drive/research/non-homogenous-data/creds/creds-openml.txt')
    #getting orchestration credentials from drive
    ex.define_orch_cred_drive('bart', '/My Drive//research/non-homogenous-data/creds/creds-colab.txt')

else:

    # DANIEL

    #getting openml credentials from drive
    ex.define_opml_cred_drive('/My Drive/Colab Notebooks/Non-Homogeneous Data/openMLAPIKey.txt')
    #getting orchestration credentials from drive
    ex.define_orch_cred_drive('test1', '/My Drive/Colab Notebooks/Non-Homogeneous Data/tabExpTrackAPIKey.txt')

Mounted at /content/drive
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
# Parameters varying
depth = {'distribution': 'int_uniform', 'min':1, 'max':11}
seed = {'distribution': 'constant', 'value': 42}
drop_type = {'distribution': 'categorical', 'values':['node_dropconnect', 'none']}
p = {'distribution': 'int_uniform', 'min':0, 'max':1}
back_n = {'distribution': 'categorical', 'values':[0, 0, 0, 1]}
hidden_dim = {'distribution': 'categorical', 'values':[1, 1, 1, 2]}
anneal = {'distribution': 'categorical', 'values':['interpolation', 'none', 'approx']}
batch_size = {'distribution': 'categorical', 'values':[16,32,64,64,64,128,256]}
epochs = {'distribution': 'categorical', 'values':[30, 60, 90]}
lr = {'distribution': 'log_uniform', 'min':0.05, 'max':0.2} # yields mean = 0.1082, median 0.1
momentum = {'distribution': 'constant', 'value': 0.9}
no_cuda = {'distribution': 'constant', 'value': False}
lr_step_size = {'distribution': 'categorical', 'values':[10, 10, 15, 20]}
gamma = {'distribution': 'constant', 'value': 0.1}




# Regression Spaces
LCN_reg_SGD_space = {
    'depth': depth,
    'seed': seed,
    'drop_type': drop_type,
    'p': p,
    'ensemble_n': {'distribution': 'constant', 'value': 1},
    'shrinkage': {'distribution': 'constant', 'value': 1},
    'back_n': back_n,
    'net_type': {'distribution': 'constant', 'value': 'locally_constant'},
    'hidden_dim': hidden_dim,
    'anneal': anneal,
    'optimizer': {'distribution': 'constant', 'value': 'SGD'},
    'batch_size': batch_size,
    'epochs': epochs,
    'lr': lr,
    'momentum': momentum,
    'no_cuda': no_cuda,
    'lr_step_size': lr_step_size,
    'gamma': gamma,
    'task': {'distribution': 'constant', 'value': 'regression'}
    }

LCN_reg_AMSGrad_space = {
    'depth': depth,
    'seed': seed,
    'drop_type': drop_type,
    'p': p,
    'ensemble_n': {'distribution': 'constant', 'value': 1},
    'shrinkage': {'distribution': 'constant', 'value': 1},
    'back_n': back_n,
    'net_type': {'distribution': 'constant', 'value': 'locally_constant'},
    'hidden_dim': hidden_dim,
    'anneal': anneal,
    'optimizer': {'distribution': 'constant', 'value': 'AMSGrad'},
    'batch_size': batch_size,
    'epochs': epochs,
    'lr': lr,
    'momentum': momentum,
    'no_cuda': no_cuda,
    'lr_step_size': lr_step_size,
    'gamma': gamma,
    'task': {'distribution': 'constant', 'value': 'regression'}
    }

LLN_reg_SGD_space = {
    'depth': depth,
    'seed': seed,
    'drop_type': drop_type,
    'p': p,
    'ensemble_n': {'distribution': 'constant', 'value': 1},
    'shrinkage': {'distribution': 'constant', 'value': 1},
    'back_n': back_n,
    'net_type': {'distribution': 'constant', 'value': 'locally_linear'},
    'hidden_dim': hidden_dim,
    'anneal': anneal,
    'optimizer': {'distribution': 'constant', 'value': 'SGD'},
    'batch_size': batch_size,
    'epochs': epochs,
    'lr': lr,
    'momentum': momentum,
    'no_cuda': no_cuda,
    'lr_step_size': lr_step_size,
    'gamma': gamma,
    'task': {'distribution': 'constant', 'value': 'regression'}
    }


LLN_reg_AMSGrad_space = {
    'depth': depth,
    'seed': seed,
    'drop_type': drop_type,
    'p': p,
    'ensemble_n': {'distribution': 'constant', 'value': 1},
    'shrinkage': {'distribution': 'constant', 'value': 1},
    'back_n': back_n,
    'net_type': {'distribution': 'constant', 'value': 'locally_linear'},
    'hidden_dim': hidden_dim,
    'anneal': anneal,
    'optimizer': {'distribution': 'constant', 'value': 'AMSGrad'},
    'batch_size': batch_size,
    'epochs': epochs,
    'lr': lr,
    'momentum': momentum,
    'no_cuda': no_cuda,
    'lr_step_size': lr_step_size,
    'gamma': gamma,
    'task': {'distribution': 'constant', 'value': 'regression'}
    }

# Classification spaces

LCN_cls_SGD_space = {
    'depth': depth,
    'seed': seed,
    'drop_type': drop_type,
    'p': p,
    'ensemble_n': {'distribution': 'constant', 'value': 1},
    'shrinkage': {'distribution': 'constant', 'value': 1},
    'back_n': back_n,
    'net_type': {'distribution': 'constant', 'value': 'locally_constant'},
    'hidden_dim': hidden_dim,
    'anneal': anneal,
    'optimizer': {'distribution': 'constant', 'value': 'SGD'},
    'batch_size': batch_size,
    'epochs': epochs,
    'lr': lr,
    'momentum': momentum,
    'no_cuda': no_cuda,
    'lr_step_size': lr_step_size,
    'gamma': gamma,
    'task': {'distribution': 'constant', 'value': 'classification'}
    }

LCN_cls_AMSGrad_space = {
    'depth': depth,
    'seed': seed,
    'drop_type': drop_type,
    'p': p,
    'ensemble_n': {'distribution': 'constant', 'value': 1},
    'shrinkage': {'distribution': 'constant', 'value': 1},
    'back_n': back_n,
    'net_type': {'distribution': 'constant', 'value': 'locally_constant'},
    'hidden_dim': hidden_dim,
    'anneal': anneal,
    'optimizer': {'distribution': 'constant', 'value': 'AMSGrad'},
    'batch_size': batch_size,
    'epochs': epochs,
    'lr': lr,
    'momentum': momentum,
    'no_cuda': no_cuda,
    'lr_step_size': lr_step_size,
    'gamma': gamma,
    'task': {'distribution': 'constant', 'value': 'classification'}
    }

LLN_cls_SGD_space = {
    'depth': depth,
    'seed': seed,
    'drop_type': drop_type,
    'p': p,
    'ensemble_n': {'distribution': 'constant', 'value': 1},
    'shrinkage': {'distribution': 'constant', 'value': 1},
    'back_n': back_n,
    'net_type': {'distribution': 'constant', 'value': 'locally_linear'},
    'hidden_dim': hidden_dim,
    'anneal': anneal,
    'optimizer': {'distribution': 'constant', 'value': 'SGD'},
    'batch_size': batch_size,
    'epochs': epochs,
    'lr': lr,
    'momentum': momentum,
    'no_cuda': no_cuda,
    'lr_step_size': lr_step_size,
    'gamma': gamma,
    'task': {'distribution': 'constant', 'value': 'classification'}
    }


LLN_cls_AMSGrad_space = {
    'depth': depth,
    'seed': seed,
    'drop_type': drop_type,
    'p': p,
    'ensemble_n': {'distribution': 'constant', 'value': 1},
    'shrinkage': {'distribution': 'constant', 'value': 1},
    'back_n': back_n,
    'net_type': {'distribution': 'constant', 'value': 'locally_linear'},
    'hidden_dim': hidden_dim,
    'anneal': anneal,
    'optimizer': {'distribution': 'constant', 'value': 'AMSGrad'},
    'batch_size': batch_size,
    'epochs': epochs,
    'lr': lr,
    'momentum': momentum,
    'no_cuda': no_cuda,
    'lr_step_size': lr_step_size,
    'gamma': gamma,
    'task': {'distribution': 'constant', 'value': 'classification'}
    }


# Testing Hyperparameter Spaces

In [5]:
ex.monte_carlo_sample_space({
    # 'depth': depth,
    # 'seed': seed,
    'drop_type': drop_type,
    # 'p': p,
    # 'ensemble_n': {'distribution': 'constant', 'value': 1},
    # 'shrinkage': {'distribution': 'constant', 'value': 1},
    # 'back_n': back_n,
    # 'net_type': {'distribution': 'constant', 'value': 'locally_linear'},
    # 'hidden_dim': hidden_dim,
    # 'anneal': anneal,
    # 'optimizer': {'distribution': 'constant', 'value': 'AMSGrad'},
    # 'batch_size': batch_size,
    # 'epochs': epochs,
    # 'lr': lr,
    # 'momentum': momentum,
    # 'no_cuda': no_cuda,
    # 'lr_step_size': lr_step_size,
    # 'gamma': gamma,
    # 'task': {'distribution': 'constant', 'value': 'classification'}
    }, 1)

sampled 1 points in the space:
{'drop_type': {'distribution': 'categorical', 'values': ['node_dropconnect', 'none']}}


[{'drop_type': 'none'}]

In [6]:
model_groups = {
    'LCN_reg_SGD':{'model':'LCN_reg_SGD', 'hype':LCN_reg_SGD_space},
    'LCN_reg_AMSGrad':{'model':'LCN_reg_AMSGrad', 'hype':LCN_reg_AMSGrad_space},
    'LLN_reg_SGD':{'model':'LLN_reg_SGD', 'hype':LLN_reg_SGD_space},
    'LLN_reg_AMSGrad':{'model':'LLN_reg_AMSGrad', 'hype':LLN_reg_AMSGrad_space},
    'LCN_cls_SGD':{'model':'LCN_cls_SGD', 'hype':LCN_cls_SGD_space},
    'LCN_cls_AMSGrad':{'model':'LCN_cls_AMSGrad', 'hype':LCN_cls_AMSGrad_space},
    'LLN_cls_SGD':{'model':'LLN_cls_SGD', 'hype':LLN_cls_SGD_space},
    'LLN_cls_AMSGrad':{'model':'LLN_cls_AMSGrad', 'hype':LLN_cls_AMSGrad_space},
}

ex.def_model_groups(model_groups)

In [7]:
ex.def_data_groups_opml()
print('automatically defined data groups:')
print(ex.data_groups.keys())

automatically defined data groups:
dict_keys(['opml_reg_purnum_group', 'opml_class_purnum_group', 'opml_reg_numcat_group', 'opml_class_numcat_group'])


In [8]:
classification_models = [k for k in model_groups.keys() if '_cls' in k]
regression_models = [k for k in model_groups.keys() if '_reg' in k]


applications = {'opml_reg_purnum_group': regression_models,
                'opml_reg_numcat_group': regression_models,
                'opml_class_purnum_group': classification_models,
                'opml_class_numcat_group': classification_models}

ex.def_applications(applications)
ex.reg_experiment('Testing_LCN_3')
# ex.reg_experiment('20230822')

existing experiment found


'existing experiment found'

In [9]:
run_info = ex.begin_run_sticky()
run_info

{'_id': '64e736dee79e7873f8e542c7', 'metrics_per_epoch': [], 'experiment_id': '64e5e073c1b33602b5f95fa9', 'experiment_name': 'Testing_LCN_3', 'mtpair_index': 113, 'mtpair_model': 'LCN_reg_AMSGrad', 'mtpair_task': '335-361104', 'is_completed': False, 'user_id': '64d3a7457658d6ec6db139d0', 'user_name': 'bart', 'hyp': {'depth': 6, 'seed': 42, 'drop_type': 'none', 'p': 1, 'ensemble_n': 1, 'shrinkage': 1, 'back_n': 0, 'net_type': 'locally_constant', 'hidden_dim': 1, 'anneal': 'approx', 'optimizer': 'AMSGrad', 'batch_size': 256, 'epochs': 60, 'lr': 0.1962106221138713, 'momentum': 0.9, 'no_cuda': False, 'lr_step_size': 20, 'gamma': 0.1, 'task': 'regression'}, 'model': 'LCN_reg_AMSGrad', 'task': '335-361104'}
4e736dee79e7873f8e542c


{'_id': '64e736dee79e7873f8e542c7',
 'metrics_per_epoch': [],
 'experiment_id': '64e5e073c1b33602b5f95fa9',
 'experiment_name': 'Testing_LCN_3',
 'mtpair_index': 113,
 'mtpair_model': 'LCN_reg_AMSGrad',
 'mtpair_task': '335-361104',
 'is_completed': False,
 'user_id': '64d3a7457658d6ec6db139d0',
 'user_name': 'bart',
 'hyp': {'depth': 6,
  'seed': 42,
  'drop_type': 'none',
  'p': 1,
  'ensemble_n': 1,
  'shrinkage': 1,
  'back_n': 0,
  'net_type': 'locally_constant',
  'hidden_dim': 1,
  'anneal': 'approx',
  'optimizer': 'AMSGrad',
  'batch_size': 256,
  'epochs': 60,
  'lr': 0.1962106221138713,
  'momentum': 0.9,
  'no_cuda': False,
  'lr_step_size': 20,
  'gamma': 0.1,
  'task': 'regression'},
 'model': 'LCN_reg_AMSGrad',
 'task': '335-361104'}

In [10]:
run_info.get('hyp')

{'depth': 6,
 'seed': 42,
 'drop_type': 'none',
 'p': 1,
 'ensemble_n': 1,
 'shrinkage': 1,
 'back_n': 0,
 'net_type': 'locally_constant',
 'hidden_dim': 1,
 'anneal': 'approx',
 'optimizer': 'AMSGrad',
 'batch_size': 256,
 'epochs': 60,
 'lr': 0.1962106221138713,
 'momentum': 0.9,
 'no_cuda': False,
 'lr_step_size': 20,
 'gamma': 0.1,
 'task': 'regression'}

In [11]:
ex.opml_load_task(run_info['mtpair_task'])

downloading task 335-361104
task different than previous task, downloading...


(       KWG KWI STRM STRN SA SB    Run2    Run3    Run4
 0        0   0    0    0  0  0  115.87  118.55  115.80
 1        0   0    0    0  0  1   78.25   79.25   79.19
 2        0   0    0    0  1  0   80.69   80.76   80.97
 3        0   0    0    0  1  1   89.90   86.75   85.58
 4        0   0    0    1  0  0  121.98  122.73  114.81
 ...     ..  ..  ...  ... .. ..     ...     ...     ...
 241595   1   1    1    0  1  1   17.77   17.77   17.77
 241596   1   1    1    1  0  0   36.03   36.04   36.03
 241597   1   1    1    1  0  1   34.82   35.27   35.27
 241598   1   1    1    1  1  0   28.49   28.44   28.45
 241599   1   1    1    1  1  1   17.79   17.77   17.77
 
 [241600 rows x 9 columns],
 0         4.755829
 1         4.371092
 2         4.392472
 3         4.446409
 4         4.754710
             ...   
 241595    2.942331
 241596    3.611998
 241597    3.591267
 241598    3.382015
 241599    2.941276
 Name: Run1, Length: 241600, dtype: float64,
 [True, True, True, True, True, T

# 1. Object for hyperparameter unpacking

In [12]:
class Hyperparams:
    def __init__(self, depth, seed, drop_type, p, ensemble_n, shrinkage, back_n, net_type, hidden_dim, anneal,
                 optimizer, batch_size, epochs, lr, momentum, no_cuda, lr_step_size, gamma, task):
        self.depth = depth
        self.seed = seed
        self.drop_type = drop_type
        self.p = p
        self.ensemble_n = ensemble_n
        self.shrinkage = shrinkage
        self.back_n = back_n
        self.net_type = net_type
        self.hidden_dim = hidden_dim
        self.anneal = anneal
        self.optimizer = optimizer
        self.batch_size = batch_size
        self.epochs = epochs
        self.lr = lr
        self.momentum = momentum
        self.no_cuda = no_cuda
        self.lr_step_size = lr_step_size
        self.gamma = gamma
        self.task = task

In [13]:
args = Hyperparams(**run_info.get('hyp'))

# 2. Creating Dataset objects

In [14]:
import pandas as pd
import numpy as np
import torch


class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, X, Y, relative_indices, tensor_type=torch.float):
        self.__X, self.__Y = X, Y

        assert isinstance(relative_indices, np.ndarray) and relative_indices.ndim == 1, "Relative indices must be a 1D NumPy array"
        self.__relative_indices = np.sort(relative_indices)

        assert isinstance(tensor_type, torch.dtype), "tensor_type must be a valid torch.dtype"
        self.__tensor_type = tensor_type

    def __len__(self):
        return len(self.__relative_indices)

    def __getitem__(self, idx):
        absolute_index = self.__relative_indices[idx]

        x, y = self.__X.iloc[absolute_index], self.__Y.iloc[absolute_index]

        x, y = torch.tensor(x.values, dtype=self.__tensor_type), torch.tensor(y.values, dtype=self.__tensor_type)

        x, y = x.unsqueeze(0), y.unsqueeze(0)

        return x, y


In [15]:
# Quick unit testing
test_x = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6],
    'b': [4, 5, 6, 8, 1, 9]
})


test_y = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6]
})

indices = np.array([2, 3, 4])

test_obj  = CustomDataset(test_x, test_y, indices)

assert torch.equal(test_obj[0][0], torch.tensor([[3, 6]], dtype=torch.float)) and torch.equal(test_obj[0][1], torch.tensor([[3]], dtype=torch.float)), 'test failed'
print('test passed')
assert torch.equal(test_obj[1][0], torch.tensor([[4, 8]], dtype=torch.float)) and torch.equal(test_obj[1][1], torch.tensor([[4]], dtype=torch.float)), 'test failed'
print('test passed')
assert torch.equal(test_obj[2][0], torch.tensor([[5, 1]], dtype=torch.float)) and torch.equal(test_obj[2][1], torch.tensor([[5]], dtype=torch.float)), 'test failed'
print('test passed')
assert torch.equal(test_obj[2][0], torch.tensor([[5, 1]], dtype=torch.float)) and torch.equal(test_obj[2][1], torch.tensor([[5]], dtype=torch.float)), 'test failed'
print('test passed')
assert len(test_obj) == len(indices), 'test failed'
print('test passed')


# Concatenating the inputs (assuming they are 2D tensors)
concatenated_X = torch.cat([test_obj[i][0] for i in range(len(test_obj))], dim=0)
concatenated_Y = torch.cat([test_obj[i][1] for i in range(len(test_obj))], dim=0)

# Expected concatenated tensors
expected_X = torch.cat([torch.tensor([[3, 6]], dtype=torch.float),
                        torch.tensor([[4, 8]], dtype=torch.float),
                        torch.tensor([[5, 1]], dtype=torch.float)], dim=0)
expected_Y = torch.cat([torch.tensor([[3]], dtype=torch.float),
                        torch.tensor([[4]], dtype=torch.float),
                        torch.tensor([[5]], dtype=torch.float)], dim=0)

# Check if the concatenated tensors are equal to the expected tensors
assert torch.equal(concatenated_X, expected_X), 'Concatenated X test failed'
assert torch.equal(concatenated_Y, expected_Y), 'Concatenated Y test failed'
print('Concatenation test passed')

test passed
test passed
test passed
test passed
test passed
Concatenation test passed


In [16]:
from sklearn.model_selection import KFold

for _ in range(3):
    kf = KFold(n_splits=3, shuffle=True, random_state=999)
    print(list(kf.split(list(range(10000))))[0][:10])
    print('----')

(array([   0,    2,    3, ..., 9995, 9996, 9999]), array([   1,    6,    8, ..., 9991, 9997, 9998]))
----
(array([   0,    2,    3, ..., 9995, 9996, 9999]), array([   1,    6,    8, ..., 9991, 9997, 9998]))
----
(array([   0,    2,    3, ..., 9995, 9996, 9999]), array([   1,    6,    8, ..., 9991, 9997, 9998]))
----


In [17]:
kf = KFold(n_splits=3, shuffle=True, random_state=999)

for i in kf.split(list(range(10000))):
  print(i[0])
  print(len(i[0]))
  print(i[1])
  print(len(i[1]))
  print('-----')

[   0    2    3 ... 9995 9996 9999]
6666
[   1    6    8 ... 9991 9997 9998]
3334
-----
[   1    5    6 ... 9996 9997 9998]
6667
[   0    2    3 ... 9993 9994 9999]
3333
-----
[   0    1    2 ... 9997 9998 9999]
6667
[   5    7   10 ... 9992 9995 9996]
3333
-----


# 3. Get train test Custom Dataset Objects

In [18]:
import pandas as pd

def get_train_test(X, y, categorical_indicator, attribute_names, train_split, seed):
    """Processes dataset
    expects the results from `opml_load_task`, 0<= train_spli <= 1, seed
    returns train CustomDataset Object, test CustomDataset Object, input_dim, output_dim
    """

    # Assert that train_split is between 0 and 1
    assert 0 <= train_split <= 1, "train_split must be between 0 and 1."

    # One hot encoding all categorical variables
    X = pd.get_dummies(X, X.columns[categorical_indicator])

    # Defining if target is categorical
    is_categorical = y.dtype.name == 'category'

    # Set the random seed for reproducibility
    np.random.seed(seed)

    # Calculate the number of training samples
    num_train_samples = int(len(X) * train_split)

    # Sample indices for the training and test data
    train_indices = np.random.choice(X.index, num_train_samples, replace=False)
    test_indices = np.setdiff1d(X.index, train_indices)


    num_columns_X = X.shape[1]
    num_columns_y = y.shape[1] if isinstance(y, pd.DataFrame) else 1

    return CustomDataset(X, y, train_indices), CustomDataset(X, y, test_indices), num_columns_X, num_columns_y



# 4. CustomDataset wrapper

In [19]:
class CustomDatasetWrapper(torch.utils.data.Dataset):
    def __init__(self, train_dataset, relative_indices):
        assert isinstance(train_dataset, CustomDataset), "train_dataset must be an instance of CustomDataset"
        assert isinstance(relative_indices, np.ndarray) and relative_indices.ndim == 1, "Relative indices must be a 1D NumPy array"
        assert len(relative_indices) <= len(train_dataset), "Length of relative_indices must not be greater than the length of train_dataset"

        self.train_dataset = train_dataset
        self.relative_indices = relative_indices

    def set_new_indices(self, new_relative_indices):
      assert isinstance(new_relative_indices, np.ndarray) and new_relative_indices.ndim == 1, "Relative indices must be a 1D NumPy array"
      assert len(new_relative_indices) <= len(self.train_dataset), "Length of relative_indices must not be greater than the length of train_dataset"
      self.relative_indices = new_relative_indices

    def __len__(self):
        return len(self.relative_indices)

    def __getitem__(self, idx):
        absolute_index = self.relative_indices[idx]

        return self.train_dataset[absolute_index]

In [20]:
# Quick unit testing for CustomDatasetWrapper
test_x = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6],
    'b': [4, 5, 6, 8, 1, 9]
})

test_y = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6]
})

indices_1 = np.array([2, 3, 4])
indices_2 = np.array([1, 2])

test_obj  = CustomDataset(test_x, test_y, indices_1)
test_outer_obj = CustomDatasetWrapper(test_obj, indices_2)

# Testing index [0]
assert torch.equal(test_outer_obj[0][0], torch.tensor([[4, 8]], dtype=torch.float)) and torch.equal(test_outer_obj[0][1], torch.tensor([[4]], dtype=torch.float)), 'test failed'
print('test passed')

# Testing index [1]
assert torch.equal(test_outer_obj[1][0], torch.tensor([[5, 1]], dtype=torch.float)) and torch.equal(test_outer_obj[1][1], torch.tensor([[5]], dtype=torch.float)), 'test failed'
print('test passed')

# Concatenating the inputs (assuming they are 2D tensors)
concatenated_X = torch.cat([test_outer_obj[i][0] for i in range(len(test_outer_obj))], dim=0)
concatenated_Y = torch.cat([test_outer_obj[i][1] for i in range(len(test_outer_obj))], dim=0)

# Expected concatenated tensors
expected_X = torch.cat([torch.tensor([[4, 8]], dtype=torch.float),
                        torch.tensor([[5, 1]], dtype=torch.float)], dim=0)
expected_Y = torch.cat([torch.tensor([[4]], dtype=torch.float),
                        torch.tensor([[5]], dtype=torch.float)], dim=0)

# Check if the concatenated tensors are equal to the expected tensors
assert torch.equal(concatenated_X, expected_X), 'Concatenated X test failed'
assert torch.equal(concatenated_Y, expected_Y), 'Concatenated Y test failed'
print('Concatenation test passed')

print('=== test 2 ====')
# New relative indices
new_indices = np.array([0, 2])

# Set new relative indices
test_outer_obj.set_new_indices(new_indices)

# Testing index [0] with new relative indices
assert torch.equal(test_outer_obj[0][0], torch.tensor([[3, 6]], dtype=torch.float)) and torch.equal(test_outer_obj[0][1], torch.tensor([[3]], dtype=torch.float)), 'test failed'
print('test passed')

# Testing index [1] with new relative indices
assert torch.equal(test_outer_obj[1][0], torch.tensor([[5, 1]], dtype=torch.float)) and torch.equal(test_outer_obj[1][1], torch.tensor([[5]], dtype=torch.float)), 'test failed'
print('test passed')

# Concatenating the inputs (assuming they are 2D tensors) with new relative indices
concatenated_X = torch.cat([test_outer_obj[i][0] for i in range(len(test_outer_obj))], dim=0)
concatenated_Y = torch.cat([test_outer_obj[i][1] for i in range(len(test_outer_obj))], dim=0)

# Expected concatenated tensors with new relative indices
expected_X = torch.cat([torch.tensor([[3, 6]], dtype=torch.float),
                        torch.tensor([[5, 1]], dtype=torch.float)], dim=0)
expected_Y = torch.cat([torch.tensor([[3]], dtype=torch.float),
                        torch.tensor([[5]], dtype=torch.float)], dim=0)

# Check if the concatenated tensors are equal to the expected tensors
assert torch.equal(concatenated_X, expected_X), 'Concatenated X test failed'
assert torch.equal(concatenated_Y, expected_Y), 'Concatenated Y test failed'
print('Concatenation test passed')


test passed
test passed
Concatenation test passed
=== test 2 ====
test passed
test passed
Concatenation test passed


# 5. Get kfold data loaders

In [40]:
from sklearn.model_selection import KFold

class kfold_dataloader_iterator():
    def __init__(self,
                 dataset,
                 n_splits=10, #kfold arguments
                 random_state=42,
                 batch_size=16, #data_loader argument
                 shuffle_kfold=True,
                 shuffle_dataloader=True):

        assert isinstance(dataset, CustomDataset), "train_dataset must be an instance of CustomDataset"
        self.__dataset = dataset
        self.__kf = KFold(n_splits=n_splits, shuffle=shuffle_kfold, random_state=42)
        self.__kf_iter = self.__kf.split(list(range(len(self.__dataset))))

        assert isinstance(batch_size, int), "Batch size must be an int"
        self.batch_size = batch_size
        self.shuffle_dataloader = shuffle_dataloader

        self.train_data = None
        self.val_data = None

    def __iter__(self):
        return self

    def __next__(self):

        train_indices, val_indices = next(self.__kf_iter)

        self.train_data = CustomDatasetWrapper(self.__dataset, train_indices)
        self.val_data = CustomDatasetWrapper(self.__dataset, val_indices)

        train_dataloader = torch.utils.data.DataLoader(self.train_data, batch_size=self.batch_size, shuffle=self.shuffle_dataloader)
        val_dataloader = torch.utils.data.DataLoader(self.val_data, batch_size=len(self.val_data), shuffle=False)

        return train_dataloader, val_dataloader






In [43]:
# Quick unit testing for kfold_dataloader_iterator
test_x = pd.DataFrame({
    'a': list(range(1, 21)),
    'b': list(range(4, 24))
})

test_y = pd.DataFrame({
    'a': list(range(1, 21))
})

indices_1 = np.array(range(test_x[test_x.columns[0]].count()))
print(f'lenght: {len(test_x)}')


# Create a CustomDataset object
test_obj = CustomDataset(test_x, test_y, indices_1)

# Create kfold_dataloader_iterator object
kfold_iterator = kfold_dataloader_iterator(test_obj, n_splits=4, batch_size=4)

# Iterate through the kfold splits and perform tests
for i, (train_dataloader, val_dataloader) in enumerate(kfold_iterator):
    print(f"Fold {i+1}:")

    # Check the length of the training and validation dataloaders
    print(f'train_dataloader.dataset = {len(train_dataloader.dataset)}')
    assert len(train_dataloader.dataset) == 15, f"Training data length in fold {i+1} is incorrect"
    print(f'val_dataloader.dataset = {len(val_dataloader.dataset)}')
    assert len(val_dataloader.dataset) == 5, f"Validation data length in fold {i+1} is incorrect"

    # You can further test individual batches or the content of the data,
    # such as checking if the data has been shuffled correctly,
    # or checking the values of specific examples within the batch.

# Check that the iteration has indeed ended
try:
    next(kfold_iterator)
except StopIteration:
    print("Iteration has ended as expected.")
else:
    print("Unexpectedly, the iteration has not ended.")


lenght: 20
Fold 1:
train_dataloader.dataset = 15
val_dataloader.dataset = 5
Fold 2:
train_dataloader.dataset = 15
val_dataloader.dataset = 5
Fold 3:
train_dataloader.dataset = 15
val_dataloader.dataset = 5
Fold 4:
train_dataloader.dataset = 15
val_dataloader.dataset = 5
Iteration has ended as expected.
